// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: PB_ISLAND_TREASURE.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PB_ISLAND_TREASURE struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	WeekBuyNum    *uint32                 `protobuf:"varint,1,req,name=week_buy_num,json=weekBuyNum" json:"week_buy_num,omitempty"`
	SellList      []*PB_TRE_SELL_LIST     `protobuf:"bytes,2,rep,name=sell_list,json=sellList" json:"sell_list,omitempty"`
	PriceList     []*PB_TRE_HISTORY_PRICE `protobuf:"bytes,3,rep,name=price_list,json=priceList" json:"price_list,omitempty"`
	InviteList    []uint32                `protobuf:"varint,4,rep,name=invite_list,json=inviteList" json:"invite_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PB_ISLAND_TREASURE) Reset() {
	*x = PB_ISLAND_TREASURE{}
	mi := &file_PB_ISLAND_TREASURE_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PB_ISLAND_TREASURE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PB_ISLAND_TREASURE) ProtoMessage() {}

func (x *PB_ISLAND_TREASURE) ProtoReflect() protoreflect.Message {
	mi := &file_PB_ISLAND_TREASURE_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PB_ISLAND_TREASURE.ProtoReflect.Descriptor instead.
func (*PB_ISLAND_TREASURE) Descriptor() ([]byte, []int) {
	return file_PB_ISLAND_TREASURE_proto_rawDescGZIP(), []int{0}
}

func (x *PB_ISLAND_TREASURE) GetWeekBuyNum() uint32 {
	if x != nil && x.WeekBuyNum != nil {
		return *x.WeekBuyNum
	}
	return 0
}

func (x *PB_ISLAND_TREASURE) GetSellList() []*PB_TRE_SELL_LIST {
	if x != nil {
		return x.SellList
	}
	return nil
}

func (x *PB_ISLAND_TREASURE) GetPriceList() []*PB_TRE_HISTORY_PRICE {
	if x != nil {
		return x.PriceList
	}
	return nil
}

func (x *PB_ISLAND_TREASURE) GetInviteList() []uint32 {
	if x != nil {
		return x.InviteList
	}
	return nil
}

var File_PB_ISLAND_TREASURE_proto protoreflect.FileDescriptor

const file_PB_ISLAND_TREASURE_proto_rawDesc = "" +
	"\n" +
	"\x18PB_ISLAND_TREASURE.proto\x12\abelfast\x1a\x1aPB_TRE_HISTORY_PRICE.proto\x1a\x16PB_TRE_SELL_LIST.proto\"\xcd\x01\n" +
	"\x12PB_ISLAND_TREASURE\x12 \n" +
	"\fweek_buy_num\x18\x01 \x02(\rR\n" +
	"weekBuyNum\x126\n" +
	"\tsell_list\x18\x02 \x03(\v2\x19.belfast.PB_TRE_SELL_LISTR\bsellList\x12<\n" +
	"\n" +
	"price_list\x18\x03 \x03(\v2\x1d.belfast.PB_TRE_HISTORY_PRICER\tpriceList\x12\x1f\n" +
	"\vinvite_list\x18\x04 \x03(\rR\n" +
	"inviteListB\fZ\n" +
	"./protobuf"

var (
	file_PB_ISLAND_TREASURE_proto_rawDescOnce sync.Once
	file_PB_ISLAND_TREASURE_proto_rawDescData []byte
)

func file_PB_ISLAND_TREASURE_proto_rawDescGZIP() []byte {
	file_PB_ISLAND_TREASURE_proto_rawDescOnce.Do(func() {
		file_PB_ISLAND_TREASURE_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_ISLAND_TREASURE_proto_rawDesc), len(file_PB_ISLAND_TREASURE_proto_rawDesc)))
	})
	return file_PB_ISLAND_TREASURE_proto_rawDescData
}

var file_PB_ISLAND_TREASURE_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PB_ISLAND_TREASURE_proto_goTypes = []any{
	(*PB_ISLAND_TREASURE)(nil),   // 0: belfast.PB_ISLAND_TREASURE
	(*PB_TRE_SELL_LIST)(nil),     // 1: belfast.PB_TRE_SELL_LIST
	(*PB_TRE_HISTORY_PRICE)(nil), // 2: belfast.PB_TRE_HISTORY_PRICE
}
var file_PB_ISLAND_TREASURE_proto_depIdxs = []int32{
	1, // 0: belfast.PB_ISLAND_TREASURE.sell_list:type_name -> belfast.PB_TRE_SELL_LIST
	2, // 1: belfast.PB_ISLAND_TREASURE.price_list:type_name -> belfast.PB_TRE_HISTORY_PRICE
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PB_ISLAND_TREASURE_proto_init() }
func file_PB_ISLAND_TREASURE_proto_init() {
	if File_PB_ISLAND_TREASURE_proto != nil {
		return
	}
	file_PB_TRE_HISTORY_PRICE_proto_init()
	file_PB_TRE_SELL_LIST_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_ISLAND_TREASURE_proto_rawDesc), len(file_PB_ISLAND_TREASURE_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_ISLAND_TREASURE_proto_goTypes,
		DependencyIndexes: file_PB_ISLAND_TREASURE_proto_depIdxs,
		MessageInfos:      file_PB_ISLAND_TREASURE_proto_msgTypes,
	}.Build()
	File_PB_ISLAND_TREASURE_proto = out.File
	file_PB_ISLAND_TREASURE_proto_goTypes = nil
	file_PB_ISLAND_TREASURE_proto_depIdxs = nil
}
