// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_21247.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_21247 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IslandId      *uint32                `protobuf:"varint,1,req,name=island_id,json=islandId" json:"island_id,omitempty"`
	MapId         *uint32                `protobuf:"varint,2,req,name=map_id,json=mapId" json:"map_id,omitempty"`
	Price         *uint32                `protobuf:"varint,3,req,name=price" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_21247) Reset() {
	*x = SC_21247{}
	mi := &file_SC_21247_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_21247) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_21247) ProtoMessage() {}

func (x *SC_21247) ProtoReflect() protoreflect.Message {
	mi := &file_SC_21247_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_21247.ProtoReflect.Descriptor instead.
func (*SC_21247) Descriptor() ([]byte, []int) {
	return file_SC_21247_proto_rawDescGZIP(), []int{0}
}

func (x *SC_21247) GetIslandId() uint32 {
	if x != nil && x.IslandId != nil {
		return *x.IslandId
	}
	return 0
}

func (x *SC_21247) GetMapId() uint32 {
	if x != nil && x.MapId != nil {
		return *x.MapId
	}
	return 0
}

func (x *SC_21247) GetPrice() uint32 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

var File_SC_21247_proto protoreflect.FileDescriptor

const file_SC_21247_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_21247.proto\x12\abelfast\"T\n" +
	"\bSC_21247\x12\x1b\n" +
	"\tisland_id\x18\x01 \x02(\rR\bislandId\x12\x15\n" +
	"\x06map_id\x18\x02 \x02(\rR\x05mapId\x12\x14\n" +
	"\x05price\x18\x03 \x02(\rR\x05priceB\fZ\n" +
	"./protobuf"

var (
	file_SC_21247_proto_rawDescOnce sync.Once
	file_SC_21247_proto_rawDescData []byte
)

func file_SC_21247_proto_rawDescGZIP() []byte {
	file_SC_21247_proto_rawDescOnce.Do(func() {
		file_SC_21247_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_21247_proto_rawDesc), len(file_SC_21247_proto_rawDesc)))
	})
	return file_SC_21247_proto_rawDescData
}

var file_SC_21247_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_21247_proto_goTypes = []any{
	(*SC_21247)(nil), // 0: belfast.SC_21247
}
var file_SC_21247_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SC_21247_proto_init() }
func file_SC_21247_proto_init() {
	if File_SC_21247_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_21247_proto_rawDesc), len(file_SC_21247_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_21247_proto_goTypes,
		DependencyIndexes: file_SC_21247_proto_depIdxs,
		MessageInfos:      file_SC_21247_proto_msgTypes,
	}.Build()
	File_SC_21247_proto = out.File
	file_SC_21247_proto_goTypes = nil
	file_SC_21247_proto_depIdxs = nil
}
